server:
  port: 8082
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  db:
    database: hm-cart
    host: 192.168.209.128 # 修改为你自己的虚拟机IP地址
    pw: 123456 # 修改为docker中的MySQL密码
  swagger:
    title: "黑马商城购物车服务文档"
    package: com.hmall.cart.controller