server:
  port: 8086
hm:
  db:
    database: hm-pay
    host: 192.168.209.128 # 修改为你自己的虚拟机IP地址
    pw: 123456 # 修改为docker中的MySQL密码
  swagger:
    title: "黑马商城支付管理服务文档"
    package: com.hmall.pay.controller
