server:
  port: 8080
spring:
  application:
    name: allbadminton
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/allbadminton?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: 81.70.132.184
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  type-aliases-package: com.lyy.allbadminton.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

lyy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: allbadminton
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tCxntXbv5aerWpUGM66
    access-key-secret: yAwif4P2umRR4MpTOGa1VieLnRQlm9
    bucket-name: sky-itcast-lyy
