package com.atguigu.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_id
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_name
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_salary
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    private Double empSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_emp.emp_age
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    private Integer empAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_id
     *
     * @return the value of t_emp.emp_id
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_id
     *
     * @param empId the value for t_emp.emp_id
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_name
     *
     * @return the value of t_emp.emp_name
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_name
     *
     * @param empName the value for t_emp.emp_name
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_salary
     *
     * @return the value of t_emp.emp_salary
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public Double getEmpSalary() {
        return empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_salary
     *
     * @param empSalary the value for t_emp.emp_salary
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public void setEmpSalary(Double empSalary) {
        this.empSalary = empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_emp.emp_age
     *
     * @return the value of t_emp.emp_age
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public Integer getEmpAge() {
        return empAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_emp.emp_age
     *
     * @param empAge the value for t_emp.emp_age
     *
     * @mbggenerated Wed Dec 18 20:39:13 CST 2024
     */
    public void setEmpAge(Integer empAge) {
        this.empAge = empAge;
    }
}